config/routes.rb
FriendFitter::Application.routes.draw do

  # Join a community
  post '/members/:id' => 'members#create', as: 'member_create'
  delete '/members/:id' => 'members#destroy', as: 'member_delete'
  resources :communities
  resources :workouts, except: [:new]
  get '/workouts/new/:id' => 'workouts#new', as: 'new_workout'
  get '/workouts/copy/:id' => 'workouts#copy', as: 'copy_workout'
  resources :exercises, except: [:new]
  get '/exercises/new/:id' => 'exercises#new', as: 'new_exercise'
  resources :workout_sessions
  resources :exercise_sessions
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  root to: 'workouts#index'
end

app/models/workout.rb
# == Schema Information
#
# Table name: workouts
#
#  id           :integer          not null, primary key
#  name         :text
#  difficulty   :text
#  posted       :boolean
#  started      :boolean
#  user_id      :integer
#  created_at   :datetime
#  updated_at   :datetime
#  community_id :integer
#

class Workout < ActiveRecord::Base
  belongs_to :user
  has_many :workout_sessions
  has_many :exercise_sessions
  belongs_to :community
  # has_many :followers, through: :workout_sessions, source: :user
  has_and_belongs_to_many :exercises

  # Validations
  validates :name, presence: true
  validates :difficulty, presence: true
  validates :user, presence: true
  validates :community, presence: true

  # Model helper functions
  def exercises_to_add
    Exercise.all - self.exercises
  end

  def add_exercise(exercise)
   self.exercises << exercise
    # add an exercise session for each user with this workout session
    participants = self.workout_sessions.map do |x|
      x.user_id
    end
    participants.each do |i|
      User.find(i).exercise_sessions << ExerciseSession.new(
        exercise_id: exercise.id,
        workout_id: self.id)
    end
  end

  ## n+1 queries - refactored in controller
  # def self.my_workouts_pending(user)
  #   my_workouts = []
  #   user.workout_sessions.each do |x|
  #     my_workouts << x.workout unless x.accomplished?
  #   end
  #   my_workouts.sort_by! { |x| x.created_at }
  #   my_workouts.reverse
  # end

  # def self.my_workouts_completed(user)
  #   my_workouts = []
  #   user.workout_sessions.each do |x|
  #     my_workouts << x.workout if x.accomplished?
  #   end
  #   my_workouts.sort_by! { |x| x.created_at }
  #   my_workouts.reverse
  # end

  # def self.other_workouts(user)
  #   Workout.order(created_at: :desc) - my_workouts_pending(user) - my_workouts_completed(user)
  # end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :get_workout, only: [:show, :edit, :update, :destroy, :copy]

  def index
    all = Workout.order(created_at: :desc).where(user: current_user).includes(:workout_sessions)
    @my_workouts_pending = []
    @my_workouts_completed = []
    all.each do |workout|
      workout.workout_sessions.each do |session|
        if session.accomplished?
          @my_workouts_completed << workout
        else
          @my_workouts_pending << workout
        end
      end
    end
    @other_workouts = all - @my_workouts_completed - @my_workouts_pending
    @communities = Community.all
  end

  def show
    @exercise = Exercise.new
    @workout_session = WorkoutSession.new
  end

  def new
    @community = Community.find(params[:id])
    @workout = Workout.new
  end

  def create
    @workout = current_user.workouts.new(workout_params)
    if @workout.save
      flash[:notice] = 'Workout saved!'
      redirect_to @workout
    else
      flash.now[:errors] = @workout.errors.full_messages.join(', ')
      render :new
    end
  end

  def copy
    new_workout = Workout.new
    new_workout.assign_attributes(
      name: @workout.name,
      difficulty: @workout.difficulty,
      community_id: @workout.community_id,
      user_id: current_user.id
      )
    if new_workout.save
      new_workout.exercises << @workout.exercises
      flash[:notice] = 'Workout copied!'
      redirect_to new_workout
    else
      flash[:errors] = new_workout.errors.full_messages.join(', ')
      redirect_to :back
    end
  end

  def edit
    # So that the form can work
    @community = Community.new
  end

  def update
    @workout.assign_attributes(workout_params)
    if params[:workout][:exercise_ids].to_i != 0
      exercise = Exercise.find(params[:workout][:exercise_ids].to_i)
      if @workout.save
        @workout.add_exercise(exercise)
        flash[:notice] = 'Workout Updated!'
        redirect_to @workout
      else
        flash.new[:errors] = @workout.errors.full_messages.join(', ')
        render :edit
      end
    else
      if @workout.save
        flash[:notice] = 'Workout Updated!'
        redirect_to @workout
      else
        flash.new[:errors] = @workout.errors.full_messages.join(', ')
        render :edit
      end
    end
  end

  def destroy
    @workout.delete
    redirect_to root_path
  end


  private

  def workout_params
    params.require(:workout).permit(:name, :difficulty, :posted, :started, :community_id)
  end

  def get_workout
    @workout = Workout.find(params[:id])
  end

end

app/helpers/workouts_helper.rb
module WorkoutsHelper

  def community_id(community, workout)
    community.id || workout.community.id
  end
end

app/views/workouts/_form.html.erb
<%= form_for @workout do |f| %>
  <div class="form-group"><%= f.label :name %><%= f.text_field :name, class: 'form-control' %></div>
  <div class="form-group"><%= f.label :difficulty %> <%= f.select :difficulty, ['easy', 'medium', 'hard'], {}, { class: 'form-control'} %></div>
  <%= f.hidden_field :community_id, value: community_id(@community, @workout) %>
  <div class="form-group"><%= f.submit 'Create', class: 'btn btn-default' %></div>
<% end %>
<%= link_to 'Back', :back %>

app/views/workouts/_workout_session.html.erb
<%= form_for workout_session, method: method, html: {class: 'form-inline'} do |f| %>
<% if workout_session.persisted? %>
  <div class="checkbox"><%= f.label :pr, 'PR' %> <%= f.check_box :pr %></div>
  <div class="form-group"><%= f.label :comment, class: 'sr-only'%><%= f.text_field :comment, class: 'form-control', placeholder: 'Comment' %></div>
  <%= f.hidden_field :accomplished, value: true %>
<% end %>
<%= f.hidden_field :workout_id, value: @workout.id %>
<div class="form-group"><%= f.submit submit, class: 'btn btn-default' %></div>
<% end %>

app/views/workouts/_workouts.html.erb
<%= link_to workout_path(workout) do %>
  <article class="workout_link">
    <h2><%= workout.name %></h2>
    <p>Owner: <%= workout.user.username %> | Mantra: <%= workout.user.mantra %> |
    Difficulty: <%= workout.difficulty %> | Status: <%= workout.started? ? 'Started' : 'Not Started' %></p>
    <h3>Participants</h3>
    <table class="table-bordered table-condensed table">
      <tr>
        <th>User</th>
        <th>Comment</th>
        <th>Mods</th>
        <th>Done</th>
        <th>PR</th>
      </tr>
      <% workout.workout_sessions.each do |session| %>
        <tr>
          <td><%= session.user.username %></td>
          <td><%= session.comment %></td>
          <td><%= session.mod_count %></td>
          <td>
            <% if session.accomplished? %>
              <span class="glyphicon glyphicon-ok"></span>
              <% end %>
          </td>
          <td>
            <% if session.pr? %>
              <span class="glyphicon glyphicon-star"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </article>
<% end %>

app/views/workouts/edit.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="well col-md-4">
    <h1>Edit <%= @workout.name %></h1>

    <%= render 'form' %>

    <%= link_to 'Back', @workout %>
  </div>
</div>

app/views/workouts/index.html.erb
<div class="jumbotron">
  <h1>My Workouts</h1>
  <p class="center">Username: <%= current_user.username %></p>
  <p class="center">Mantra: <%= current_user.mantra %></p>
</div>

<div class="row well">
  <% if @my_workouts_pending.count > 0 || @my_workouts_completed.count > 0 %>
    <section class="col-md-4 side_border">
      <h2>Pending Workouts</h2>
      <% @my_workouts_pending.each do |workout| %>
          <%= render partial: 'workouts', locals: {workout: workout} %>
      <% end %>
    </section>
    <section class="col-md-4">
      <h2>Completed Workouts</h2>
      <% @my_workouts_completed.each do |workout| %>
          <%= render partial: 'workouts', locals: {workout: workout} %>
      <% end %>
    </section>
  <% else %>
    <section class="col-md-8 side_border">
      <h2>Welcome to FriendFitter!</h2>
      <p class="center">Look to the right and join a Community to start working out.</p>
      <p class="center">Or if you don't find one, create your own Community!</p>
    </section>
  <% end %>

  <section class="col-md-4 side_border_left">
    <article>
      <h1>Communities</h1>
      <%= button_to 'Create a community', new_community_path, class: 'btn btn-default', method: 'get' %><br>
      <table class="table-bordered table-condensed table">
        <tr>
          <th>Name</th>
          <th>Members</th>
          <th>Workouts</th>
        </tr>
        <% @communities.each do |community| %>
          <tr>
            <td><%= link_to community.name, community %></td>
            <td><%= community.members_count %></td>
            <td><%= community.workouts_count %></td>
          </tr>
        <% end %>
      </table>
    </article>
    <h1>New Workouts</h1>
    <% @other_workouts.each do |workout| %>
      <% if current_user.community_member?(workout.community) %>
        <%= render partial: 'workouts', locals: {workout: workout} %>
      <% end %>
    <% end %>
  </section>
</div>

app/views/workouts/new.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="well col-md-4">
    <h1>Create a Workout!</h1>

    <%= render 'form' %>
  </div>
</div>

app/views/workouts/show.html.erb
<div class="jumbotron">
  <h1 class="left"><%= @workout.name %></h1>
  <p>Community: <%= link_to @workout.community.name, @workout.community %> |
  Creator: <%= @workout.user.username %> |
  Difficulty: <%= @workout.difficulty %> |
  Workout Status: <%= @workout.started? ? 'Started' : 'Not Started' %></p>
  <% if current_user == @workout.user && !@workout.started? %>
    <nav class="col-md-4">
      <ul class="nav nav-pills nav-justified">
        <li><%= link_to 'Edit Workout', edit_workout_path, class: 'btn btn-default' %></li>
        <li><%=link_to 'Delete Workout',  @workout, method: 'delete', confirm: 'Are you sure?', class: 'btn btn-default' %></li>
      </ul>
    </nav>
  <% end %>
  <%= link_to 'Copy workout', copy_workout_path(@workout), class: 'btn btn-default' %>
</div>
<div class="row well no_padding">
  <article class="col-md-7 side_border">
    <h2>Exercises</h2>
    <% @workout.exercises.includes(:exercise_sessions).each do |exercise| %>
      <p><span class="ex_name"><%= link_to exercise.name, exercise %></span>
       | Detail: <%= exercise.detail %> | Duration: <%= exercise.duration %></p>
      <table class="table-bordered table-condensed table">
        <tr>
          <th>User</th>
          <th>Modified</th>
          <th>Comment</th>
          <th>Done</th>
          <th>PR</th>
        </tr>
        <% exercise.exercise_sessions.includes(:workout, :user).each do |exercise_session| %>
          <% if exercise_session.workout == @workout %>
            <tr>
              <td><%= exercise_session.user.username %></td>
              <% if exercise_session.modified? %>
                <td><%= link_to exercise_session.exercise_modified.name,  exercise_session.exercise_modified %></td>
              <% else %>
                <td>Nope</td>
              <% end %>
              <td><%= exercise_session.comment %></td>
              <td>
                <% if exercise_session.accomplished? %>
                  <span class="glyphicon glyphicon-ok"></span>
                <% end %>
              </td>
              <td>
                <% if exercise_session.pr? %>
                  <span class="glyphicon glyphicon-star"></span>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
        </table>
        <% exercise.exercise_sessions.each do |exercise_session| %>
          <% if exercise_session.workout == @workout && exercise_session.user == current_user && !exercise_session.accomplished? %>
            <%= form_for exercise_session, method: 'put', html: {class: 'form-inline'} do |f| %>
              <div class="form-group">
                <%= f.collection_select :exercise_mod, Exercise.all, :id, :name, {prompt: true}, { class: 'form-control'} %>
              </div>
              <div class="form-group"><%= f.label :comment, class: 'sr-only' %><%= f.text_field :comment, class: 'form-control', placeholder: 'Comment' %></div>
              <div class="checkbox"><%= f.label :pr,  'PR' %> <%= f.check_box :pr %></div>
              <%= f.hidden_field :accomplished, value: true %>
              <%= f.submit 'Did it!', class: 'btn btn-default' %>
              <br><br>
            <% end %>
          <% end %>
        <% end %>
      <% end %>

    <% if current_user.participating?(@workout) %>
      <%= form_for @workout, html: {class: 'form-inline'} do |f| %>
        <div class="form-group">
          <%= f.collection_select :exercise_ids, @workout.exercises_to_add, :id, :name, {}, { class: 'form-control'} %>
        </div>
        <%= f.submit 'Add to workout', class: 'btn btn-default' %>
      <% end %>
      <%= link_to "Don't see your exercise, create it!", new_exercise_path(@workout) %>
    <% end %><br><br>
    <% if !@workout.workout_sessions.map(&:user_id).include?(current_user.id) && current_user.community_member?(@workout.community) %>
      <br><br><p>Join the workout!</p>
      <%= render partial: 'workout_session', locals: {workout_session: @workout_session, method: 'post', submit: 'Join'} %><br><br>
    <% end %>

  </article>
  <article class="col-md-5">
    <h2>Participants</h2>
    <table class="table-bordered table-condensed table">
      <tr>
        <th>User</th>
        <th>Comment</th>
        <th>Mods</th>
        <th>Done</th>
        <th>PR</th>
      </tr>
      <% @workout.workout_sessions.includes(:user, :workout).each do |session| %>
        <tr>
          <td><%= session.user.username %></td>
          <td><%= session.comment %></td>
          <td><%= session.mod_count %></td>
          <td>
            <% if session.accomplished? %>
              <span class="glyphicon glyphicon-ok"></span>
            <% end %>
          </td>
          <td>
            <% if session.pr? %>
              <span class="glyphicon glyphicon-star"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
      <% @workout.workout_sessions.each do |session| %>
        <% if session.user.id == current_user.id %>
          <% if !session.accomplished? %>
            <%= render partial: 'workout_session', locals: {workout_session: session, method: 'put', submit: 'Complete'} %><br>
            <%= link_to 'Quit Workout', session, method: 'delete', confirm: 'Are you sure', class: 'btn btn-default' %><br><br>
          <% end %>
        <% end%>
    <% end %>
  </article>
</div>