config/routes.rb
FriendFitter::Application.routes.draw do

  # Join a community
  post '/members/:id' => 'members#create', as: 'member_create'
  delete '/members/:id' => 'members#destroy', as: 'member_delete'
  resources :communities
  resources :workouts, except: [:new]
  get '/workouts/new/:id' => 'workouts#new', as: 'new_workout'
  get '/workouts/copy/:id' => 'workouts#copy', as: 'copy_workout'
  resources :exercises, except: [:new]
  get '/exercises/new/:id' => 'exercises#new', as: 'new_exercise'
  resources :workout_sessions
  resources :exercise_sessions
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  root to: 'workouts#index'
end

app/models/community.rb
# == Schema Information
#
# Table name: communities
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Community < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :workouts
  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 160 }

  # Helper methods
  def members_count
    self.users.count
  end

  def workouts_count
    self.workouts.count
  end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :get_community, only: [:edit, :update, :show]

  def show
  end

  def new
    @community = Community.new
  end

  def create
    @community = Community.new(community_params)
    if @community.save
      flash[:notice] = 'Community created!'
      redirect_to @community
    else
      flash.now[:errors] = @community.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit
  end

  def update
    @community.assign_attributes(community_params)
    if @community.save
      flash[:notice] = 'Community updated!'
      redirect_to @community
    else
      flash.now[:errors] = @community.errors.full_messages.join(', ')
      render :edit
    end
  end

  private
  def community_params
    params.require(:community).permit(:name, :description)
  end

  def get_community
    @community = Community.find(params[:id])
  end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_form.html.erb
<%= form_for @community do |f| %>
  <div class="form-group"><%= f.label :name %><%= f.text_field :name, class: 'form-control' %></div>
  <div class="form-group"><%= f.label :description %><%= f.text_field :description, class: 'form-control' %></div>
  <div class="form-group"><%= f.submit 'Create Community', class: 'btn btn-default' %></div>
<% end %>

app/views/communities/edit.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="well col-md-4">
    <h1>Edit <%= @community.name %></h1>

    <%= render 'form' %>

    <%= link_to 'Back', @community %>
  </div>
</div>

app/views/communities/new.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="well col-md-4">
    <h1>Create a new community</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/communities/show.html.erb
<div class="jumbotron">
  <h1><%= @community.name %></h1>
  <p><%= @community.description %></p>
  <% if current_user.community_member?(@community) %>
    <!-- Can't add a workout unless they are a member -->
    <%= link_to 'Add a workout', new_workout_path(@community), class: 'btn btn-default' %><br><br>
    <%= button_to 'Quit community', member_delete_path(@community), method: 'delete', confirm: 'Are you sure?', class: 'btn btn-default' %>
  <% else %>
    <%= button_to 'Join community', member_create_path(@community) , class: 'btn btn-default' %>
  <% end %>
</div>

<div class="row well">
  <section class="col-md-6 side_border">
    <h2>Members</h2>
    <article>
      <table class="table-bordered table-condensed table">
        <tr>
          <th>User</th>
          <th>Mantra</th>
          <th>Workouts Completed</th>
          <th>PRs</th>
        </tr>
        <% @community.users.includes(:workout_sessions).each do |user| %>
          <tr>
            <td><%= user.username %></td>
            <td><%= user.mantra %></td>
            <td><%= user.finished_count %></td>
            <td><%= user.pr_count %></td>
          </tr>
        <% end %>
      </table>
    </article>
  </section>
  <section class="col-md-6">
    <h2>Workouts</h2>
    <article>
      <table class="table-bordered table-condensed table">
        <tr>
          <th>Workout</th>
          <th>Difficulty</th>
          <th>Started</th>
        </tr>
        <% @community.workouts.each do |workout| %>
          <tr>
            <td><%= link_to workout.name, workout %></td>
            <td><%= workout.difficulty %></td>
            <td><%= workout.started? ? 'Yes' : 'No' %></td>
          </tr>
        <% end %>
      </table>
    </article>
  </section>
</div>