config/routes.rb
FriendFitter::Application.routes.draw do

  # Join a community
  post '/members/:id' => 'members#create', as: 'member_create'
  delete '/members/:id' => 'members#destroy', as: 'member_delete'
  resources :communities
  resources :workouts, except: [:new]
  get '/workouts/new/:id' => 'workouts#new', as: 'new_workout'
  get '/workouts/copy/:id' => 'workouts#copy', as: 'copy_workout'
  resources :exercises, except: [:new]
  get '/exercises/new/:id' => 'exercises#new', as: 'new_exercise'
  resources :workout_sessions
  resources :exercise_sessions
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  root to: 'workouts#index'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  username               :text             default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  mantra                 :text
#  created_at             :datetime
#  updated_at             :datetime
#  provider               :string(255)
#  uid                    :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :workout_sessions
  has_many :exercise_sessions
  has_many :workouts
  has_and_belongs_to_many :communities
  # has_many :exercises, through: :exercise_sessions

  # username validation
  validates :username, presence: true
  validates :username, uniqueness: true

  # Helper methods
  def pr_count
    sum_array = self.workout_sessions.map { |x| x.pr? ? 1 : 0 }
    sum_array.reduce(:+)
  end

  def finished_count
    sum_array = self.workout_sessions.map { |x| x.accomplished? ? 1 : 0 }
    sum_array.reduce(:+)
  end

  def community_member?(community)
    self.communities.include?(community)
  end

  def participating?(workout)
    # current user has a workout session that points to this workout
    array = self.workout_sessions.includes(:workout).map do |x|
      x.workout.id == workout.id
    end
    array.index(true) ? true : false
  end

  # omniauth helper methods
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.username = auth.info.nickname
      user.email = auth.info.email
      user.mantra = auth.info.description
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :get_exercise, only: [:show, :edit, :update, :destroy]

  def index
    @exercises = Exercise.all
  end

  def show
  end

  def new
    @exercise = Exercise.new
    @workout = Workout.find(params[:id])
  end

  def create
    # Don't ask
    workout_id = eval(params[:workout_ids].first[0])[:value]
    workout = Workout.find(workout_id)
    @exercise = Exercise.new(exercise_params)
    @exercise.assign_attributes(video_id: 'video_id')
    if @exercise.save
      workout.add_exercise(@exercise)
      flash[:notice] = 'Exercise Saved!'
      redirect_to workout
    else
      flash[:errors] = @exercise.errors.full_messages.join(', ')
      redirect_to :back
    end
  end

  def edit
  end

  def update
    @exercise.assign_attributes(exercise_params)
    @exercise.assign_attributes(video_id: 'video_id')
    if @exercise.save
      flash[:notice] = 'Exercise Updated!'
      redirect_to @exercise
    else
      flash.now[:errors] = @exercise.errors.full_messages.join(', ')
      render :edit
    end
  end

  def destroy
    @exercise.delete
    redirect_to exercises_path
  end


  private

  def exercise_params
    params.require(:exercise).permit(:name, :detail, :duration, :started)
  end

  def get_exercise
    @exercise = Exercise.find(params[:id])
  end


  def youtube_search(keyword)
    developer_key = ENV["GOOGLE_KEY"]
    youtube_api_service_name = "youtube"
    youtube_api_version = "v3"

    client = Google::APIClient.new(:key => developer_key,
                                   :authorization => nil,
                                   :application_name => 'API Project',
                                   :application_version => '1.0')

    youtube = client.discovered_api(youtube_api_service_name, youtube_api_version)
    # Call the search.list method to retrieve results matching the specified
    # query term.
    search_response = client.execute!(
      :api_method => youtube.search.list,
      :parameters => {q: keyword, maxResults: 5, part: 'id,snippet'}
    )

    # Sort through the search_response and return video_id of first video
    search_response.data.items.each do |search_result|
      if search_result.id.kind == 'youtube#video'
        return search_result.id.videoId
        break
      end
    end
  end

end

app/helpers/exercises_helper.rb
module ExercisesHelper

end

app/views/exercises/_form.html.erb
<%= form_for @exercise do |f| %>
  <div class="form-group"><%= f.label :name %><%= f.text_field :name, class: 'form-control' %></div>
  <div class="form-group"><%= f.label :detail %><%= f.text_field :detail, class: 'form-control' %></div>
  <div class="form-group"><%= f.label :duration %><%= f.text_field :duration, class: 'form-control' %></div>
  <% if @workout %>
    <%= hidden_field :workout_ids, value: @workout.id %>
  <% end %>
  <div class="form-group"><%= f.submit submit, class: 'btn btn-default' %></div>
<% end %>

app/views/exercises/edit.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="well col-md-5">
    <h2>Edit <%= @exercise.name %></h2>
    <%= render partial: 'form', locals: {submit: 'Update exercise'} %>
  </div>
</div>

app/views/exercises/index.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-4 well"><h1>All Exercises</h1></div>
</div>
<div class="row">
  <div class="col-md-1"></div>
  <div class="well col-md-4">
    <ul>
      <% @exercises.each do |exercise| %>
        <li><%= link_to exercise.name, exercise %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/exercises/new.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="well col-md-4">
    <h1>New Exercise</h1>
    <%= render partial: 'form', locals: {submit: 'Create exercise'} %>
  </div>
</div>

app/views/exercises/show.html.erb
<div class="jumbotron">
  <h1><%= @exercise.name %></h1>
  <p>Detail: <%= @exercise.detail %></p>
  <p>Duration: <%= @exercise.duration %></p>
  <nav>
    <ul>
      <li><%= link_to 'Edit Exercise', edit_exercise_path %></li>
      <li><%= link_to 'Delete Exercise', @exercise, method: 'delete', confirm: 'Are you sure?' %></li>
    </ul>
  </nav>
</div>

<div class="row">
  <div class="well col-md-4">
    <h2>Workouts</h2>
    <ul>
      <% @exercise.workouts.each do |workout| %>
        <li><%= link_to workout.name, workout %></li>
      <% end %>
    </ul>
  </div>
  <div class="col-md-6">
    <iframe class="youtube-player" type="text/html" width="640" height="385" src="http://www.youtube.com/embed/<%= @exercise.video_id %>" allowfullscreen frameborder="0">
    </iframe>
  </div>
</div>